title: Docker .NET Lab
tagline: A brand new course on Learning Lab
description: >-
  Learn how to use Docker to run, build, deploy & run on production a .NET Core
  ASP App
template:
  repo: docker-dotnet-lab-template
  name: docker-dotnet-lab-
  description: The template repository for the Docker .NET Lab course on Learning Lab.
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: Getting Started
    description: How to run postgres
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: createIssue
        title: Getting started
        body: 01-getting-started.md
