title: Docker .NET Lab
tagline: A brand new course on Learning Lab
description: >-
  Learn how to use Docker to run, build, deploy & run on production a .NET Core
  ASP App
template:
  repo: docker-dotnet-lab-template
  name: docker-dotnet-lab
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
  - title: New step
    actions:
      - type: createIssue
        title: A new issue
        body: a-response-file.md
